/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ConverterType.
* @enum {}
* @readonly
*/
export default class ConverterType {
    
        /**
         * value: "REMOVE_GROUPED_HEADER"
         * @const
         */
        "REMOVE_GROUPED_HEADER" = "REMOVE_GROUPED_HEADER";

    
        /**
         * value: "FILL_EMPTY_CELLS"
         * @const
         */
        "FILL_EMPTY_CELLS" = "FILL_EMPTY_CELLS";

    
        /**
         * value: "REMOVE_COLUMN_BY_INDEX"
         * @const
         */
        "REMOVE_COLUMN_BY_INDEX" = "REMOVE_COLUMN_BY_INDEX";

    
        /**
         * value: "REMOVE_ROW_BY_INDEX"
         * @const
         */
        "REMOVE_ROW_BY_INDEX" = "REMOVE_ROW_BY_INDEX";

    

    /**
    * Returns a <code>ConverterType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ConverterType} The enum <code>ConverterType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

