/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConverterType from './ConverterType';

/**
 * The SplitRowStructure model module.
 * @module model/SplitRowStructure
 * @version 1.10.0
 */
class SplitRowStructure {
    /**
     * Constructs a new <code>SplitRowStructure</code>.
     * @alias module:model/SplitRowStructure
     * @param converterType {module:model/ConverterType} 
     * @param columnIndex {Number} 
     */
    constructor(converterType, columnIndex) { 
        
        SplitRowStructure.initialize(this, converterType, columnIndex);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, converterType, columnIndex) { 
        obj['converterType'] = converterType;
        obj['columnIndex'] = columnIndex;
    }

    /**
     * Constructs a <code>SplitRowStructure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SplitRowStructure} obj Optional instance to populate.
     * @return {module:model/SplitRowStructure} The populated <code>SplitRowStructure</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SplitRowStructure();

            if (data.hasOwnProperty('converterType')) {
                obj['converterType'] = ConverterType.constructFromObject(data['converterType']);
            }
            if (data.hasOwnProperty('columnIndex')) {
                obj['columnIndex'] = ApiClient.convertToType(data['columnIndex'], 'Number');
            }
            if (data.hasOwnProperty('delimiter')) {
                obj['delimiter'] = ApiClient.convertToType(data['delimiter'], 'String');
            }
            if (data.hasOwnProperty('startRow')) {
                obj['startRow'] = ApiClient.convertToType(data['startRow'], 'Number');
            }
            if (data.hasOwnProperty('endRow')) {
                obj['endRow'] = ApiClient.convertToType(data['endRow'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SplitRowStructure</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SplitRowStructure</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SplitRowStructure.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['delimiter'] && !(typeof data['delimiter'] === 'string' || data['delimiter'] instanceof String)) {
            throw new Error("Expected the field `delimiter` to be a primitive type in the JSON string but got " + data['delimiter']);
        }

        return true;
    }


}

SplitRowStructure.RequiredProperties = ["converterType", "columnIndex"];

/**
 * @member {module:model/ConverterType} converterType
 */
SplitRowStructure.prototype['converterType'] = undefined;

/**
 * @member {Number} columnIndex
 */
SplitRowStructure.prototype['columnIndex'] = undefined;

/**
 * @member {String} delimiter
 */
SplitRowStructure.prototype['delimiter'] = undefined;

/**
 * @member {Number} startRow
 */
SplitRowStructure.prototype['startRow'] = undefined;

/**
 * @member {Number} endRow
 */
SplitRowStructure.prototype['endRow'] = undefined;






export default SplitRowStructure;

