/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConverterType from './ConverterType';

/**
 * The Structure model module.
 * @module model/Structure
 * @version 1.0.2
 */
class Structure {
    /**
     * Constructs a new <code>Structure</code>.
     * @alias module:model/Structure
     * @param converterType {module:model/ConverterType} 
     */
    constructor(converterType) { 
        
        Structure.initialize(this, converterType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, converterType) { 
        obj['converterType'] = converterType;
    }

    /**
     * Constructs a <code>Structure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Structure} obj Optional instance to populate.
     * @return {module:model/Structure} The populated <code>Structure</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Structure();

            if (data.hasOwnProperty('converterType')) {
                obj['converterType'] = ConverterType.constructFromObject(data['converterType']);
            }
            if (data.hasOwnProperty('columnIndex')) {
                obj['columnIndex'] = ApiClient.convertToType(data['columnIndex'], ['Number']);
            }
            if (data.hasOwnProperty('rowIndex')) {
                obj['rowIndex'] = ApiClient.convertToType(data['rowIndex'], ['Number']);
            }
            if (data.hasOwnProperty('startRow')) {
                obj['startRow'] = ApiClient.convertToType(data['startRow'], 'Number');
            }
            if (data.hasOwnProperty('startColumn')) {
                obj['startColumn'] = ApiClient.convertToType(data['startColumn'], 'Number');
            }
            if (data.hasOwnProperty('endRow')) {
                obj['endRow'] = ApiClient.convertToType(data['endRow'], 'Number');
            }
            if (data.hasOwnProperty('endColumn')) {
                obj['endColumn'] = ApiClient.convertToType(data['endColumn'], 'Number');
            }
            if (data.hasOwnProperty('headerNames')) {
                obj['headerNames'] = ApiClient.convertToType(data['headerNames'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Structure</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Structure</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Structure.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['columnIndex'])) {
            throw new Error("Expected the field `columnIndex` to be an array in the JSON data but got " + data['columnIndex']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['rowIndex'])) {
            throw new Error("Expected the field `rowIndex` to be an array in the JSON data but got " + data['rowIndex']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['headerNames'])) {
            throw new Error("Expected the field `headerNames` to be an array in the JSON data but got " + data['headerNames']);
        }

        return true;
    }


}

Structure.RequiredProperties = ["converterType"];

/**
 * @member {module:model/ConverterType} converterType
 */
Structure.prototype['converterType'] = undefined;

/**
 * @member {Array.<Number>} columnIndex
 */
Structure.prototype['columnIndex'] = undefined;

/**
 * @member {Array.<Number>} rowIndex
 */
Structure.prototype['rowIndex'] = undefined;

/**
 * @member {Number} startRow
 */
Structure.prototype['startRow'] = undefined;

/**
 * @member {Number} startColumn
 */
Structure.prototype['startColumn'] = undefined;

/**
 * @member {Number} endRow
 */
Structure.prototype['endRow'] = undefined;

/**
 * @member {Number} endColumn
 */
Structure.prototype['endColumn'] = undefined;

/**
 * @member {Array.<String>} headerNames
 */
Structure.prototype['headerNames'] = undefined;






export default Structure;

